import { Inter, Alex_Brush, Montserrat } from 'next/font/google'
import './globals.css'

const alexBrush = Alex_Brush({
  weight: ['400'],
  subsets: ['latin'],
  variable: '--font-alexBrush'
});

const montserrat = Montserrat({
  weight: ['100', '200', '300', '400', '500', '700', '800' '900'],
  subsets: ['latin'],
  variable: '--font-montserrat'
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}
